# WebSocket 实时数据服务开发环境配置

environment: development

websocket:
  host: "localhost"
  port: 8765
  max_connections: 100
  max_subscriptions_per_client: 50
  heartbeat_interval: 60.0
  max_message_size: 1048576  # 1MB
  ping_interval: 30.0
  ping_timeout: 30.0
  close_timeout: 5.0
  max_queue: 16

service_discovery:
  backend: none
  consul_host: localhost
  consul_port: 8500
  service_name: websocket-server-dev
  health_check_interval: 30.0
  heartbeat_interval: 30.0

load_balancing:
  strategy: round_robin
  rate_limit_rpm: 300
  burst_size: 50
  sticky_sessions: false

scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 80.0
  target_memory_utilization: 85.0
  target_connections_per_instance: 80
  scale_up_cooldown: 60.0
  scale_down_cooldown: 120.0
  evaluation_interval: 30.0

security:
  enable_auth: false
  auth_token: "dev-token-123"
  allowed_origins:
    - "*"
  ssl_enabled: false
  ssl_cert_path: null
  ssl_key_path: null
  rate_limit_enabled: false

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
  file_path: "logs/websocket-server-dev.log"
  max_file_size: 10485760  # 10MB
  backup_count: 3
  console_output: true

monitoring:
  enabled: true
  metrics_port: 9091
  metrics_path: "/metrics"
  health_check_path: "/health"
  readiness_check_path: "/ready"
  prometheus_enabled: false
  grafana_enabled: false

cache:
  enabled: true
  redis_host: localhost
  redis_port: 6379
  redis_db: 1
  redis_password: null
  max_size: 1000
  ttl: 600.0
  cleanup_interval: 120.0

database:
  enabled: false
  host: localhost
  port: 5432
  database: websocket_dev
  username: dev_user
  password: "dev_password"
  pool_size: 5
  max_overflow: 10