# WebSocket实时数据服务配置文件

server:
  host: "0.0.0.0"
  port: 8765
  max_connections: 1000
  max_subscriptions_per_client: 100
  ping_interval: 20.0
  ping_timeout: 20.0
  close_timeout: 10.0
  max_size: 1048576  # 1MB
  max_queue: 32

datasource:
  source_type: "mock"  # mock, qmt, tdx, yahoo
  update_interval: 1.0
  batch_size: 100
  retry_attempts: 3
  retry_delay: 1.0
  
  # QMT配置（当source_type为qmt时生效）
  qmt_host: "localhost"
  qmt_port: 8000
  qmt_account: ""
  qmt_password: ""
  
  # TDX配置（当source_type为tdx时生效）
  tdx_server: "119.147.212.81"
  tdx_port: 7709
  
  # Yahoo Finance配置（当source_type为yahoo时生效）
  yahoo_timeout: 10.0
  yahoo_retry_delay: 5.0

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/websocket_server.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5

security:
  enable_auth: false
  auth_token: "your-secret-token-here"
  allowed_origins:
    - "*"
  rate_limit: 100
  rate_limit_window: 1.0
  
  # SSL配置
  ssl_enabled: false
  ssl_cert_path: "certs/server.crt"
  ssl_key_path: "certs/server.key"

cache:
  enabled: true
  max_size: 1000
  ttl: 300.0  # 5分钟
  cleanup_interval: 60.0  # 1分钟

monitoring:
  enabled: true
  metrics_port: 9090
  metrics_path: "/metrics"
  health_check_path: "/health"
  
  # 告警配置
  alert_webhook: "https://your-webhook-url.com/alerts"
  alert_threshold:
    connection_count: 800
    error_rate: 0.05
    latency_p99: 1000  # 毫秒